# Generated by Django 5.2.17 on 2026-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional — shown to the other side of a claim once a date is claimed.', max_length=30),
        ),
        migrations.AddField(
            model_name='slot',
            name='preferred_time',
            field=models.CharField(blank=True, help_text='Optional — e.g. "around 6pm" or "after school pickup".', max_length=50),
        ),
    ]
